name: parrot
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  go_router: ^5.1.1
  js: ^0.6.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  go_router_builder: ^1.0.15
  mockito: ^5.3.2

flutter:
  uses-material-design: true
