name: parrot
description: Chrome extension to send the currently open URL to Slack
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  js: ^0.6.7
  go_router: ^12.1.1
  encrypt: ^5.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  mockito: ^5.4.2
  go_router_builder: ^2.3.0

flutter:
  uses-material-design: true
